# Generated by Django 4.1.4 on 2023-02-08 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adSoyad', models.CharField(max_length=50)),
                ('telefon', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('fiyatbilgisi', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
