# Generated by Django 4.1.4 on 2023-02-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hizmetler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hizmet_img',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Surat Yükle'),
        ),
        migrations.AlterField(
            model_name='article',
            name='adSoyad',
            field=models.CharField(max_length=50, verbose_name='Ad we Familyanyz'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Hyzmatynyz Barada Açyklama'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fiyatbilgisi',
            field=models.CharField(max_length=50, verbose_name='Hyzmatynyzyn Bahasy'),
        ),
        migrations.AlterField(
            model_name='article',
            name='telefon',
            field=models.IntegerField(verbose_name='Telefon No'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Hyzmatynyzyn Ady'),
        ),
    ]
