# Generated by Django 4.1.4 on 2023-02-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hizmetler', '0003_commentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='comment_content',
            field=models.TextField(verbose_name='Yorum içerigi'),
        ),
    ]
