# Generated by Django 4.1.4 on 2023-02-25 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hizmetler', '0004_alter_commentmodel_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hizmetler.article', verbose_name='Hyzmat'),
        ),
    ]
