# Generated by Django 4.1.4 on 2023-02-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hizmetler', '0005_alter_commentmodel_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='comment_avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
