# Generated by Django 4.1.4 on 2023-03-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hizmetler', '0006_commentmodel_comment_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Hyzmatynyz Barada'),
        ),
        migrations.AlterField(
            model_name='article',
            name='telefon',
            field=models.CharField(max_length=50, verbose_name='Telefon No'),
        ),
    ]
