# Generated by Django 4.1.4 on 2023-04-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hizmetler', '0008_article_like_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='like_resim',
            field=models.ImageField(default='resim/kalp.png', upload_to=''),
        ),
    ]
