# Generated by Django 4.1.4 on 2023-04-08 21:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hizmetler', '0011_remove_article_likes_article_like_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='like_status',
        ),
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='article_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
