# Generated by Django 4.1.4 on 2023-05-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hizmetler', '0017_alter_article_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
