# Generated by Django 4.1.4 on 2023-05-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hizmetler', '0018_alter_article_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
