# Generated by Django 4.1.4 on 2023-05-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hizmetler', '0020_alter_article_hizmet_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hizmet_img',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Surat Yükle'),
        ),
    ]
