# Generated by Django 4.1.4 on 2023-05-03 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sorusor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soran_avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('adSoyad', models.CharField(max_length=50, verbose_name='Ad we Familyanyz')),
                ('title', models.CharField(max_length=50, verbose_name='Sory Temasy')),
                ('content', models.TextField(verbose_name='Soru İçerigi')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('like', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
