# Generated by Django 4.1.4 on 2023-05-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soruSor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorusor',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
