# Generated by Django 4.1.4 on 2023-05-04 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soruSor', '0002_alter_sorusor_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='cevaplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adSoyad', models.CharField(max_length=50)),
                ('cevap_avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('cevap_tarih', models.DateTimeField(auto_now_add=True)),
                ('soru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cevap', to='soruSor.sorusor', verbose_name='cevap')),
            ],
        ),
    ]
