# Generated by Django 4.1.4 on 2023-05-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soruSor', '0003_cevaplar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cevaplar',
            name='cevap_content',
            field=models.TextField(default='+1', verbose_name='Cevap icerigi'),
        ),
    ]
