# Generated by Django 4.1.4 on 2023-05-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soruSor', '0005_sorusor_likes_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorusor',
            name='cevap_sayi',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
