# Generated by Django 4.1.4 on 2023-05-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soruSor', '0007_cevaplar_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorusor',
            name='soru_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
