# Generated by Django 4.1.4 on 2023-05-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soruSor', '0008_sorusor_soru_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorusor',
            name='soru_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
